### PR TITLE
Member roster update

### PR DESCRIPTION
**Pull request by manforowicz**
Added new members to the roster.

### CODE REVIEW

**Comment by AlnisS** [comment]
Looks like the new folks might not be added alphabetical by last name - would it be possible to alphabetize? Thanks!

**Comment by manforowicz** [comment]
Instead of alphabetizing by hand in 5 minutes, I spent 30 minutes writing a Python script to do it for me :laughing:.  I also committed that.

The script outputs in JSON, so all the keys in the members list are now quoted. Hopefully that's fine.

**Comment by AlnisS** [comment]
Excellent work! Looks great to me. :shipit: 

In the future, it might be helpful to add the resize command to a README or something (about workflow for adding members).

Thanks!

**Review by AlnisS — APPROVED** [review]
:shipit:

**Comment by AlnisS** [comment]
@manforowicz I deleted the branch. It's still possible to restore it if needed using the above "restore branch" button. This avoids having issues with history, as future commits in this branch would conflict with the squashed commit.

**Pull request merged**
